lane :bonjour do

  scan(
    code_coverage: true
  )
  xcov


  #if UI.confirm("Sure ?")
  #  UI.success "Cooollllllll !"
  #else
  #  UI.error "Hmmm ?"
  #end
end

lane :deploy do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "shemana/fastlane-demo",
      name: version, # nom de la version sur github
      api_token: ENV["GITHUB_TOKEN"],
      tag_name: "v#{version}",
      description: changelog_from_git_commits(),
      commitish: "master"
    )

  end
end
